"""scheme_explain_cache

Revision ID: 17c97579c351
Revises: ddea6836315d
Create Date: 2026-05-20 06:23:31.835552

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '17c97579c351'
down_revision: Union[str, Sequence[str], None] = 'ddea6836315d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_explain_cache',
    sa.Column('scheme_id', sa.String(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('explanation_text_hi', sa.Text(), nullable=False),
    sa.Column('explanation_audio_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scheme_id', 'length')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheme_explain_cache')
    # ### end Alembic commands ###
