"""feedback message_id fk

Revision ID: f3b84b9913e6
Revises: 17c97579c351
Create Date: 2026-05-27 05:45:56.524196

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3b84b9913e6'
down_revision: Union[str, Sequence[str], None] = '17c97579c351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('message_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_feedback_message_id'), 'feedback', ['message_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'messages', ['message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_message_id'), table_name='feedback')
    op.drop_column('feedback', 'message_id')
    # ### end Alembic commands ###
